apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::508548371596:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-29T19:41:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "832"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e64a17ee-f21b-4288-b519-e734900db443
