apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::508548371596:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1E19O2C7B3D0
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-30T03:25:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "890"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 1c704277-7736-4697-aa38-5a36c5a0d799
