apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::508548371596:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-28T23:43:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "938"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9c9d014b-9941-460c-91d3-f6b5c55047ba
