apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::508548371596:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1LDB35LRJLZEM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::508548371596:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-30T04:47:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "783"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c57214f7-c921-4696-8e89-19618fb8d7e6
